[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
primaryColor = "#A020F0"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2B2B35"
textColor = "#C5C6C7"
font = "sans serif"
